In [1]:
#importing the Libraries#
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Reading the Dataset#
dataset=pd.read_csv('insurance_pre.csv')

In [3]:
#what saved in this file#
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
#create dummy data set. #drop a column#
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
#what saved in this file#
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [6]:
#catogorical data convert to numerical data#
dataset=dataset.astype(int)

In [7]:
#what saved in this file#
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [8]:
#show all columns in dataset#
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [9]:
#independent variable means input.  #split input variables. #dataset assigned to independent variable#
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [10]:
#what saved in this file#
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [11]:
#dependent variable means output.  #split output variables. #dataset assigned to dependent variable#
dependent=dataset[['charges']]

In [12]:
#what saved in this file#
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [13]:
from sklearn.ensemble import GradientBoostingRegressor

In [14]:
#Model creation#
from sklearn.model_selection import GridSearchCV
param_grid = {'loss':['squared_error','absolute_error','huber','quantile'],
              'max_features':[10,100,1000,2000,3000],'criterion':['friedman_mse','squared_error']}

grid=GridSearchCV(GradientBoostingRegressor(), param_grid, refit=True, verbose=3,n_jobs=-1)

#fitting the model for grid search
grid.fit(independent,dependent)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\Users\anandha rishi\anaconda3\Lib\site-packages\sklearn\ensemble\_gb.py:437: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=GradientBoostingRegressor(), n_jobs=-1,
             param_grid={'criterion': ['friedman_mse', 'squared_error'],
                         'loss': ['squared_error', 'absolute_error', 'huber',
                                  'quantile'],
                         'max_features': [10, 100, 1000, 2000, 3000]},
             verbose=3)

In [15]:
#Print best parameter afterr tuning#
#Print(grid.best_params_)

re=grid.cv_results_

print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'friedman_mse', 'loss': 'squared_error', 'max_features': 100}:

In [16]:
table=pd.DataFrame.from_dict(re)

In [17]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_loss,param_max_features,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.289973,0.024010,0.011062,0.006193,friedman_mse,squared_error,10,"{'criterion': 'friedman_mse', 'loss': 'squared...",0.878293,0.796756,0.892461,0.846087,0.861403,0.855000,0.033042,9
1,0.255892,0.007592,0.009377,0.007656,friedman_mse,squared_error,100,"{'criterion': 'friedman_mse', 'loss': 'squared...",0.878298,0.796743,0.892461,0.846455,0.861547,0.855101,0.033033,1
2,0.253144,0.006250,0.009376,0.007656,friedman_mse,squared_error,1000,"{'criterion': 'friedman_mse', 'loss': 'squared...",0.878300,0.796758,0.892370,0.846087,0.861418,0.854987,0.033022,10
3,0.280402,0.027702,0.003127,0.006253,friedman_mse,squared_error,2000,"{'criterion': 'friedman_mse', 'loss': 'squared...",0.878289,0.796758,0.892370,0.846262,0.861540,0.855044,0.033016,6
4,0.260679,0.005961,0.003612,0.006081,friedman_mse,squared_error,3000,"{'criterion': 'friedman_mse', 'loss': 'squared...",0.878238,0.796756,0.892370,0.846285,0.861604,0.855051,0.033010,5
5,0.703223,0.021854,0.006250,0.007655,friedman_mse,absolute_error,10,"{'criterion': 'friedman_mse', 'loss': 'absolut...",0.818608,0.758927,0.866324,0.828060,0.854891,0.825362,0.037460,30
6,0.584746,0.049068,0.007736,0.009761,friedman_mse,absolute_error,100,"{'criterion': 'friedman_mse', 'loss': 'absolut...",0.876159,0.757584,0.873087,0.829249,0.853913,0.837999,0.043552,21
7,0.553896,0.004338,0.000000,0.000000,friedman_mse,absolute_error,1000,"{'criterion': 'friedman_mse', 'loss': 'absolut...",0.853546,0.761273,0.869389,0.831682,0.854891,0.834156,0.038380,25
8,0.577906,0.012037,0.006250,0.007655,friedman_mse,absolute_error,2000,"{'criterion': 'friedman_mse', 'loss': 'absolut...",0.875958,0.760805,0.862767,0.832988,0.854615,0.837427,0.040775,22
9,0.608806,0.047397,0.003125,0.006250,friedman_mse,absolute_error,3000,"{'criterion': 'friedman_mse', 'loss': 'absolut...",0.855299,0.761273,0.859531,0.829249,0.853914,0.831853,0.036853,26
10,0.828469,0.028500,0.003125,0.006250,friedman_mse,huber,10,"{'criterion': 'friedman_mse', 'loss': 'huber',...",0.888884,0.788803,0.885819,0.843083,0.864716,0.854261,0.036643,19
11,0.800801,0.006465,0.009376,0.007655,friedman_mse,huber,100,"{'criterion': 'friedman_mse', 'loss': 'huber',...",0.888891,0.788803,0.885645,0.843503,0.864716,0.854312,0.036590,15
12,0.822154,0.020288,0.003125,0.006251,friedman_mse,huber,1000,"{'criterion': 'friedman_mse', 'loss': 'huber',...",0.888875,0.788414,0.885654,0.843506,0.864716,0.854233,0.036728,20
13,0.729671,0.009917,0.006254,0.007660,friedman_mse,huber,2000,"{'criterion': 'friedman_mse', 'loss': 'huber',...",0.888875,0.788705,0.886178,0.843505,0.864716,0.854396,0.036713,13
14,0.721180,0.020226,0.003125,0.006251,friedman_mse,huber,3000,"{'criterion': 'friedman_mse', 'loss': 'huber',...",0.888842,0.788072,0.886528,0.843431,0.864716,0.854318,0.036999,14
15,0.539837,0.037287,0.009375,0.007655,friedman_mse,quantile,10,"{'criterion': 'friedman_mse', 'loss': 'quantil...",0.528713,0.648252,0.641568,0.663994,0.680458,0.632597,0.053654,38
16,0.590727,0.038090,0.006938,0.008566,friedman_mse,quantile,100,"{'criterion': 'friedman_mse', 'loss': 'quantil...",0.528738,0.686747,0.641596,0.669992,0.680458,0.641507,0.058467,31
17,0.624476,0.016405,0.009375,0.007655,friedman_mse,quantile,1000,"{'criterion': 'friedman_mse', 'loss': 'quantil...",0.528754,0.653945,0.641568,0.659759,0.680458,0.632897,0.053568,36
18,0.633228,0.046026,0.004806,0.006313,friedman_mse,quantile,2000,"{'criterion': 'friedman_mse', 'loss': 'quantil...",0.528714,0.661586,0.641438,0.660572,0.680458,0.634554,0.054341,34
19,0.611900,0.028199,0.006250,0.007655,friedman_mse,quantile,3000,"{'criterion': 'friedman_mse', 'loss': 'quantil...",0.528773,0.686747,0.641551,0.653104,0.680458,0.638127,0.057184,32
20,0.234373,0.000028,0.012500,0.006250,squared_error,squared_error,10,"{'criterion': 'squared_error', 'loss': 'square...",0.878340,0.796758,0.892370,0.846285,0.861435,0.855038,0.033018,7
21,0.241112,0.009599,0.003125,0.006250,squared_error,squared_error,100,"{'criterion': 'squared_error', 'loss': 'square...",0.878293,0.796743,0.892461,0.846285,0.861555,0.855067,0.033042,3
22,0.236229,0.002247,0.006250,0.007655,squared_error,squared_error,1000,"{'criterion': 'squared_error', 'loss': 'square...",0.878384,0.796743,0.892370,0.846285,0.861548,0.855066,0.033034,4
23,0.234373,0.000034,0.009376,0.007655,squared_error,squared_error,2000,"{'criterion': 'squared_error', 'loss': 'square...",0.878202,0.796756,0.892370,0.846262,0.861547,0.855027,0.033004,8
24,0.236848,0.014793,0.009376,0.007656,squared_error,squared_error,3000,"{'criterion': 'squared_error', 'loss': 'square...",0.878289,0.796758,0.892461,0.846262,0.861596,0.855073,0.033038,2
25,0.603204,0.042058,0.009374,0.007654,squared_error,absolute_error,10,"{'criterion': 'squared_error', 'loss': 'absolu...",0.867413,0.760979,0.862024,0.832870,0.854276,0.835512,0.039076,23
26,0.542153,0.009093,0.007160,0.008886,squared_error,absolute_error,100,"{'criterion': 'squared_error', 'loss': 'absolu...",0.850215,0.758969,0.862210,0.831152,0.852923,0.831094,0.037449,27
27,0.565953,0.034624,0.012500,0.006250,squared_error,absolute_error,1000,"{'criterion': 'squared_error', 'loss': 'absolu...",0.850211,0.758927,0.859531,0.829249,0.847996,0.829183,0.036478,29
28,0.646782,0.008759,0.007782,0.006988,squared_error,absolute_error,2000,"{'criterion': 'squared_error', 'loss': 'absolu...",0.843789,0.760538,0.870094,0.831026,0.847996,0.830689,0.037270,28
29,0.646954,0.015349,0.003469,0.006115,squared_error,absolute_error,3000,"{'criterion': 'squared_error', 'loss': 'absolu...",0.861336,0.769648,0.862210,0.830750,0.847411,0.834271,0.034276,24
30,0.800645,0.006244,0.006251,0.007655,squared_error,huber,10,"{'criterion': 'squared_error', 'loss': 'huber'...",0.888865,0.788688,0.885692,0.843508,0.864716,0.854294,0.036633,16
31,0.805473,0.015847,0.006250,0.007655,squared_error,huber,100,"{'criterion': 'squared_error', 'loss': 'huber'...",0.888889,0.788501,0.886198,0.843107,0.864716,0.854282,0.036816,18
32,0.736713,0.024826,0.006250,0.007655,squared_error,huber,1000,"{'criterion': 'squared_error', 'loss': 'huber'...",0.888850,0.788803,0.886450,0.843511,0.864716,0.854466,0.036721,11
33,0.746696,0.015994,0.006250,0.007655,squared_error,huber,2000,"{'criterion': 'squared_error', 'loss': 'huber'...",0.888885,0.788292,0.886101,0.843440,0.864716,0.854287,0.036854,17
34,0.797250,0.083469,0.011748,0.006052,squared_error,huber,3000,"{'criterion': 'squared_error', 'loss': 'huber'...",0.888831,0.788705,0.886475,0.843322,0.864716,0.854410,0.036768,12
35,0.993031,0.092685,0.043991,0.057493,squared_error,quantile,10,"{'criterion': 'squared_error', 'loss': 'quanti...",0.528795,0.645968,0.642042,0.654082,0.680458,0.630269,0.052475,40
36,0.899168,0.096575,0.009487,0.002698,squared_error,quantile,100,"{'criterion': 'squared_error', 'loss': 'quanti...",0.528736,0.653006,0.642240,0.659008,0.680458,0.632690,0.053451,37
37,0.853870,0.157242,0.009036,0.012314,squared_error,quantile,1000,"{'criterion': 'squared_error', 'loss': 'quanti...",0.528755,0.643152,0.637141,0.662279,0.680458,0.630357,0.053032,39
38,0.990989,0.052428,0.005530,0.006868,squared_error,quantile,2000,"{'criterion': 'squared_error', 'loss': 'quanti...",0.528747,0.675743,0.636166,0.661758,0.680458,0.636574,0.056074,33
39,0.915394,0.103787,0.009378,0.007657,squared_error,quantile,3000,"{'criterion': 'squared_error', 'loss': 'quanti...",0.528729,0.656522,0.637001,0.666304,0.680458,0.633803,0.054406,35

In [18]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("children:"))
sex_male_input=int(input("sex Male 0 or 1:"))
smoker_yes_input=int(input("smoker yes 0 or 1:"))

Age: 32
BMI: 43
children: 2
sex Male 0 or 1: 0
smoker yes 0 or 1: 1

In [19]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[43029.49849958]

C:\Users\anandha rishi\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(