In [1]:
#importing the Libraries#
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Reading the Dataset#
dataset=pd.read_csv('insurance_pre.csv')

In [3]:
#what saved in this file#
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
#create dummy data set. #drop a column#
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
#what saved in this file#
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [6]:
#catogorical data convert to numerical data#
dataset=dataset.astype(int)

In [7]:
#what saved in this file#
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [8]:
#show all columns in dataset#
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [9]:
#independent variable means input.  #split input variables. #dataset assigned to independent variable#
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [10]:
#what saved in this file#
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [11]:
#dependent variable means output.  #split output variables. #dataset assigned to dependent variable#
dependent=dataset[['charges']]

In [12]:
#what saved in this file#
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [13]:
#machine learning algorithms provider is sklearn #split train set and test set#
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test=train_test_split(independent, dependent,test_size=0.30,random_state=0)

In [14]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
from sklearn.ensemble import GradientBoostingRegressor
#Model creation#
from sklearn.model_selection import GridSearchCV
param_grid = {'loss':['squared_error','absolute_error','huber','quantile'],
              'max_features':[10,100,1000,2000,3000],'criterion':['friedman_mse','squared_error']}

grid=GridSearchCV(GradientBoostingRegressor(), param_grid, refit=True, verbose=3,n_jobs=-1)

#fitting the model for grid search
grid.fit(independent,dependent)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\Users\anandha rishi\anaconda3\Lib\site-packages\sklearn\ensemble\_gb.py:437: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=GradientBoostingRegressor(), n_jobs=-1,
             param_grid={'criterion': ['friedman_mse', 'squared_error'],
                         'loss': ['squared_error', 'absolute_error', 'huber',
                                  'quantile'],
                         'max_features': [10, 100, 1000, 2000, 3000]},
             verbose=3)

In [16]:
#Print best parameter afterr tuning#
#Print(grid.best_params_)

re=grid.cv_results_

print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'squared_error', 'loss': 'squared_error', 'max_features': 100}:

In [17]:
table=pd.DataFrame.from_dict(re)

In [18]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_loss,param_max_features,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.247972,0.012170,0.006250,7.654714e-03,friedman_mse,squared_error,10,"{'criterion': 'friedman_mse', 'loss': 'squared...",0.878327,0.796743,0.892461,0.846263,0.861604,0.855079,0.033049,2
1,0.251474,0.015787,0.018032,1.400148e-02,friedman_mse,squared_error,100,"{'criterion': 'friedman_mse', 'loss': 'squared...",0.878245,0.796756,0.892461,0.846087,0.861596,0.855029,0.033042,6
2,0.242824,0.006965,0.009377,7.656447e-03,friedman_mse,squared_error,1000,"{'criterion': 'friedman_mse', 'loss': 'squared...",0.878186,0.796743,0.892370,0.846285,0.861604,0.855038,0.033008,4
3,0.235057,0.005010,0.012502,6.251074e-03,friedman_mse,squared_error,2000,"{'criterion': 'friedman_mse', 'loss': 'squared...",0.878293,0.796743,0.892370,0.846087,0.861604,0.855019,0.033034,7
4,0.237302,0.005824,0.015626,4.909339e-07,friedman_mse,squared_error,3000,"{'criterion': 'friedman_mse', 'loss': 'squared...",0.878195,0.796743,0.892461,0.846087,0.861236,0.854944,0.033026,10
5,0.699231,0.020739,0.003127,6.253910e-03,friedman_mse,absolute_error,10,"{'criterion': 'friedman_mse', 'loss': 'absolut...",0.864201,0.757584,0.866548,0.831682,0.853913,0.834786,0.040521,22
6,0.736889,0.028445,0.003125,6.250477e-03,friedman_mse,absolute_error,100,"{'criterion': 'friedman_mse', 'loss': 'absolut...",0.849821,0.757584,0.866548,0.829249,0.854657,0.831572,0.038907,29
7,0.711926,0.025428,0.008776,8.035586e-03,friedman_mse,absolute_error,1000,"{'criterion': 'friedman_mse', 'loss': 'absolut...",0.849807,0.761273,0.859623,0.830043,0.854657,0.831081,0.036319,30
8,0.699581,0.026326,0.003125,6.250191e-03,friedman_mse,absolute_error,2000,"{'criterion': 'friedman_mse', 'loss': 'absolut...",0.859342,0.757563,0.862213,0.829710,0.853956,0.832557,0.039210,27
9,0.663240,0.020917,0.009376,7.655239e-03,friedman_mse,absolute_error,3000,"{'criterion': 'friedman_mse', 'loss': 'absolut...",0.857963,0.763423,0.862214,0.833185,0.853915,0.834140,0.036738,24
10,0.822349,0.013056,0.006250,7.655064e-03,friedman_mse,huber,10,"{'criterion': 'friedman_mse', 'loss': 'huber',...",0.888860,0.788803,0.886571,0.843500,0.864716,0.854490,0.036744,12
11,0.809596,0.018043,0.006250,7.655239e-03,friedman_mse,huber,100,"{'criterion': 'friedman_mse', 'loss': 'huber',...",0.888850,0.788501,0.886480,0.843442,0.864716,0.854398,0.036838,14
12,0.827302,0.018601,0.003125,6.250477e-03,friedman_mse,huber,1000,"{'criterion': 'friedman_mse', 'loss': 'huber',...",0.888885,0.788705,0.886090,0.843493,0.864716,0.854378,0.036701,15
13,0.812738,0.018183,0.003125,6.250191e-03,friedman_mse,huber,2000,"{'criterion': 'friedman_mse', 'loss': 'huber',...",0.888860,0.788705,0.886200,0.843344,0.864716,0.854365,0.036724,16
14,0.830661,0.011357,0.000000,0.000000e+00,friedman_mse,huber,3000,"{'criterion': 'friedman_mse', 'loss': 'huber',...",0.888850,0.788688,0.886122,0.842941,0.864716,0.854264,0.036739,20
15,0.617344,0.019784,0.009375,7.654850e-03,friedman_mse,quantile,10,"{'criterion': 'friedman_mse', 'loss': 'quantil...",0.528788,0.653349,0.641438,0.648920,0.680458,0.630591,0.052578,40
16,0.559196,0.060054,0.009377,7.655979e-03,friedman_mse,quantile,100,"{'criterion': 'friedman_mse', 'loss': 'quantil...",0.528788,0.657175,0.641595,0.661787,0.680458,0.633961,0.054027,34
17,0.618725,0.025029,0.003125,6.250572e-03,friedman_mse,quantile,1000,"{'criterion': 'friedman_mse', 'loss': 'quantil...",0.528747,0.656969,0.641552,0.663138,0.680458,0.634173,0.054167,33
18,0.616878,0.036263,0.003125,6.249905e-03,friedman_mse,quantile,2000,"{'criterion': 'friedman_mse', 'loss': 'quantil...",0.528770,0.657145,0.641618,0.654338,0.680458,0.632466,0.053343,36
19,0.615742,0.018142,0.006251,7.655298e-03,friedman_mse,quantile,3000,"{'criterion': 'friedman_mse', 'loss': 'quantil...",0.528720,0.686747,0.641533,0.665707,0.680458,0.640633,0.058080,31
20,0.230809,0.008445,0.012501,6.250573e-03,squared_error,squared_error,10,"{'criterion': 'squared_error', 'loss': 'square...",0.878261,0.796743,0.892370,0.846285,0.861548,0.855041,0.033016,3
21,0.243010,0.011624,0.006250,7.654947e-03,squared_error,squared_error,100,"{'criterion': 'squared_error', 'loss': 'square...",0.878290,0.796758,0.892370,0.846456,0.861536,0.855082,0.033006,1
22,0.221663,0.005797,0.009375,7.655006e-03,squared_error,squared_error,1000,"{'criterion': 'squared_error', 'loss': 'square...",0.878215,0.796743,0.892370,0.846087,0.861540,0.854991,0.033020,8
23,0.227913,0.007480,0.000000,0.000000e+00,squared_error,squared_error,2000,"{'criterion': 'squared_error', 'loss': 'square...",0.878245,0.796743,0.892370,0.846263,0.861540,0.855032,0.033015,5
24,0.227724,0.002329,0.001549,3.098011e-03,squared_error,squared_error,3000,"{'criterion': 'squared_error', 'loss': 'square...",0.878204,0.796743,0.892370,0.846087,0.861540,0.854989,0.033018,9
25,0.662217,0.018705,0.003125,6.250286e-03,squared_error,absolute_error,10,"{'criterion': 'squared_error', 'loss': 'absolu...",0.858279,0.757584,0.866548,0.831682,0.847411,0.832301,0.039138,28
26,0.670967,0.043505,0.009376,7.655123e-03,squared_error,absolute_error,100,"{'criterion': 'squared_error', 'loss': 'absolu...",0.877023,0.757563,0.857656,0.832988,0.847411,0.834528,0.041067,23
27,0.667995,0.025019,0.009370,7.650575e-03,squared_error,absolute_error,1000,"{'criterion': 'squared_error', 'loss': 'absolu...",0.862837,0.761273,0.866548,0.829710,0.848813,0.833836,0.038517,25
28,0.652715,0.018170,0.006251,7.655298e-03,squared_error,absolute_error,2000,"{'criterion': 'squared_error', 'loss': 'absolu...",0.857151,0.760807,0.869304,0.828060,0.852419,0.833548,0.038764,26
29,0.661467,0.029899,0.015626,5.955694e-07,squared_error,absolute_error,3000,"{'criterion': 'squared_error', 'loss': 'absolu...",0.873235,0.757584,0.859613,0.831026,0.852936,0.834879,0.040984,21
30,0.823170,0.016074,0.006250,7.654539e-03,squared_error,huber,10,"{'criterion': 'squared_error', 'loss': 'huber'...",0.888875,0.788705,0.886185,0.843511,0.864716,0.854399,0.036714,13
31,0.809773,0.017408,0.009375,7.654733e-03,squared_error,huber,100,"{'criterion': 'squared_error', 'loss': 'huber'...",0.888885,0.788803,0.886571,0.843514,0.864716,0.854498,0.036748,11
32,0.839887,0.038347,0.004757,6.286302e-03,squared_error,huber,1000,"{'criterion': 'squared_error', 'loss': 'huber'...",0.888846,0.788689,0.885812,0.843348,0.864683,0.854276,0.036658,19
33,0.777377,0.077221,0.009376,7.655123e-03,squared_error,huber,2000,"{'criterion': 'squared_error', 'loss': 'huber'...",0.888861,0.788501,0.886116,0.843401,0.864716,0.854319,0.036779,18
34,0.826303,0.050862,0.003125,6.250477e-03,squared_error,huber,3000,"{'criterion': 'squared_error', 'loss': 'huber'...",0.888826,0.788803,0.885806,0.843507,0.864683,0.854325,0.036603,17
35,0.618670,0.044089,0.001621,3.241253e-03,squared_error,quantile,10,"{'criterion': 'squared_error', 'loss': 'quanti...",0.528746,0.646887,0.636380,0.665199,0.680458,0.631534,0.053575,38
36,0.617050,0.039438,0.015626,1.087356e-06,squared_error,quantile,100,"{'criterion': 'squared_error', 'loss': 'quanti...",0.528778,0.648831,0.637877,0.664644,0.680458,0.632118,0.053640,37
37,0.631131,0.035166,0.006250,7.654714e-03,squared_error,quantile,1000,"{'criterion': 'squared_error', 'loss': 'quanti...",0.528775,0.648570,0.640113,0.658960,0.680458,0.631375,0.053045,39
38,0.614996,0.048241,0.009657,7.901312e-03,squared_error,quantile,2000,"{'criterion': 'squared_error', 'loss': 'quanti...",0.528766,0.652400,0.637387,0.665236,0.680458,0.632849,0.053947,35
39,0.618340,0.025948,0.010049,8.296593e-03,squared_error,quantile,3000,"{'criterion': 'squared_error', 'loss': 'quanti...",0.528793,0.645447,0.645475,0.672538,0.680458,0.634542,0.054723,32

In [19]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("children:"))
sex_male_input=int(input("sex Male 0 or 1:"))
smoker_yes_input=int(input("smoker yes 0 or 1:"))

Age: 32
BMI: 43
children: 2
sex Male 0 or 1: 0
smoker yes 0 or 1: 1

In [20]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[43029.49849958]

C:\Users\anandha rishi\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(